### PR TITLE
New tool: Probe center

### PR DESCRIPTION
**Pull request by Tom-TBT**
Added functionnalities to probe the receptive field of neurons.
The probe center is an oval that oscilate between a low and high
intensity grey, and that we move with the mouse to detect were the
recorded neuron respond.
Therefore it need a live display.

Modifications:
**QDSpy_GUI_main_ui
- added the tab and the buttons for the probe_center
**QDSpy_GUI_main.py
- added a function OnClick_btnProbeStart() called when the probe button
is pressed
- copied and adapt runStim() for the probe center
- updated keyPressEvent(), closeEvent() and updateAll() to behave like
runStim with the probe center
**QDSpy_core.py
- copied function associated with the PRESENTATION and adapt it for the
PROBE_CENTER
**QDSpy_multiprocessing:
- Added probe_center to the different enumerations.
**QDSpy_probeCenter:
Contain the probeCenter class and a main function to run the probe
center. Inside it I use openGL functions to try to keep the probe center
located on the mouse pointer (it doesn't work every time...)

### CODE REVIEW

**Comment by Tom-TBT** [comment]
Hi,
Your software looks promising and our lab (Asari's lab in EMBL Monterotondo) want to use it.
Unfortunately it missed this functionnality, so I added it. This probe center need live update of the window. I know that the idea of the software is to have pre_compiled stimuli, but it should not disturb the rest of the software.

Of course it might need rearrangement of the code and corrections, but this version seems to work.

Hope you will like it,
Tom Boissonnet

**Comment by teuler** [comment]
Hi Tom,

thanks for the suggestion. I'll have a closer look in the next couple of days.
You used the latest version I uploaded a few days ago? Have you tested your modifications also for the new overlay screen mode? I'll get back to you soon.

Best 
Thomas

P.S.: One thing I saw in your code that probably should be modified - the direct OpenGL calls. I tried to keep all low-level graphics parts in the files in the Graphics folder; this will allow later to switch to a more modern graphics API (i.e. Volcan) w/o changing most of the code.

**Comment by Tom-TBT** [comment]
I saw today the new updates, but it seems to work the same.
About the overlay, I just tried as you mentionned it, but it crash before the GUI even show up. I'll look at it later if you want. What is it supposed to do exactly ?
Also I'm not exactly sure how it would manage several windows. I just take the last one in the list and draw the probe center on it.

And about the direct call to openGL, I did this because the coordinate system of the window change after the presentation of a stimulus. So I tried to set them directly before my script, but it doesn't work every time.
I don't have a good solution for this so far, you can comment the OpenGL calls and look how it behave, you will understand better what I mean.

Finally, I don't know if you have internal documents about the general functionning of the program (like UML diagrams), but if you don't mind to share I would be happy to have a look !

Bests,
Tom

**Comment by teuler** [comment]
> About the overlay, I just tried as you mentionned it, but it crash before the GUI even show up. I'll look > at it later if you want. What is it supposed to do exactly ?

I tested it on my notebook - I assume you had only one screen attached when you got the crash. It assumes that you have at least two screen, so don't worry about this right now.
Screen overlay will allow presenting a stimulus on two lightcrafters with different LEDs, enabling more than 3 colours. This is relevant e.g. for species like zebrafish. This is for a collaboration with Tom Baden at U Sussex.

> Also I'm not exactly sure how it would manage several windows. I just take the last one in the list and 
> draw the probe center on it.
I'll look into this.

> And about the direct call to openGL, I did this because the coordinate system of the window change 
> after the presentation of a stimulus. So I tried to set them directly before my script, but it doesn't work 
> every time.
> I don't have a good solution for this so far, you can comment the OpenGL calls and look how it 
> behave, you will understand better what I mean.
The commands may be nescessary but they could be encapulated in a general function in "renderer_opengl.py".

> Finally, I don't know if you have internal documents about the general functionning of the program 
> (like UML diagrams), but if you don't mind to share I would be happy to have a look !
The program grew over the past years therefore there was no general "plan". I try to complete the documentation on qdspy.eulerlab.de over time.

Best
Thomas 
Bests,
Tom

**Comment by teuler** [comment]
Hi Tom,

please check out the branch "experimental". I integrated your function, changing it a bit to fit better into the structure of QDspy:

- I integrated the GUI in the tab "Tools"
- When "Start probing center" is pressed, the spot appears. It can now be moved (dragged) with the left mouse button pressed. Changing the spot parameters in the GUI changes the spot immediately, without having to leaving the mode. This way, the RF size can be roughly explored. The probing mode can be left by either pressing the right mouse button (saving the position to the log), or by pressing "Abort" in the GUI.

Code:
- from your module, I removed all OpenGL code, using instead the QDSpy interface to the stimulus stage -- these are mainly the objects "Stage" (dealing with all presention and scaling parameters), "View" (the presentation window handling), and "Batch" (a pyglet-derived OpenGL rendering pipeline). I have not (yet) removed calls to the pyglet API - ideally, these would also be encapulated in a separate module. This is something for my to do on "rainy days" or in case a more general interface for adding external functions to QDSpy is needed to be implemented.
- I prepared QDSpy at a few places to allow for other interactive modes in the future.
- I have not yet checked if the probing mode gets along with screen overlays.

What do you think?
Best
Thomas

**Comment by Tom-TBT** [comment]
Hi Thomas,
it looks much better like this, and way more functional with the on-fly changes of the probe !
Thanks a lot for your help, if I find anything to fix I'll notify you.

Best,
Tom

**Comment by teuler** [comment]
Hi Tom,
thanks for your inspiration and first implementation. The people in my lab love it :-)
In the next release, I'll describe the change and acknowledge you. If you find bugs or have suggestions for features, please let me know. I'll close this request now.
Best
Thomas

**Pull request closed without merging**
